# Generated by Django 4.2.3 on 2023-07-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0003_alter_payment_amount'),
        ('order_management', '0003_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_management.payment'),
        ),
    ]
