# Generated by Django 4.2.3 on 2023-07-12 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_customer_user'),
        ('order_management', '0004_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer'),
            preserve_default=False,
        ),
    ]
