# Generated by Django 4.2.3 on 2023-07-12 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment_management', '0001_initial'),
        ('order_management', '0005_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shipment_management.shipment'),
            preserve_default=False,
        ),
    ]
