# Generated by Django 4.2.3 on 2023-07-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cartmanager', '0002_cart_product_remove_cart_products_cart_products'),
        ('order_management', '0006_order_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipment',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cartmanager.cart'),
            preserve_default=False,
        ),
    ]
